### ISSUE TITLE
`fatal: unknown user: striparr`

### ISSUE THREAD

**Issue by zx8** [mikenye/docker-striparr#4]
Using the following `docker-compose` config:

```yaml
services:
  striparr:
    image: mikenye/striparr
    container_name: striparr
    environment:
      - PUID=1024
      - PGID=100
    ports:
      - 40000:40000
    volumes:
      - /opt/movies:/movies
    restart: unless-stopped
```

I get the following error:

```sh
$ docker-compose logs striparr
Attaching to striparr
striparr                | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
striparr                | [s6-init] ensuring user provided files have correct perms...exited 0.
striparr                | [fix-attrs.d] applying ownership & permissions fixes...
striparr                | [fix-attrs.d] done.
striparr                | [cont-init.d] executing container initialization scripts...
striparr                | [cont-init.d] 01-striparr: executing...
striparr                | addgroup: gid '100' in use
striparr                | adduser: unknown group striparr
striparr                | [cont-init.d] 01-striparr: exited 1.
striparr                | [cont-init.d] done.
striparr                | [services.d] starting services
striparr                | [services.d] done.
striparr                | [listener] s6-envuidgid: fatal: unknown user: striparr
striparr                | [worker] s6-envuidgid: fatal: unknown user: striparr
striparr                | [listener] s6-envuidgid: fatal: unknown user: striparr
striparr                | [worker] s6-envuidgid: fatal: unknown user: striparr
striparr                | [listener] s6-envuidgid: fatal: unknown user: striparr
striparr                | [worker] s6-envuidgid: fatal: unknown user: striparr
striparr                | [listener] s6-envuidgid: fatal: unknown user: striparr
striparr                | [worker] s6-envuidgid: fatal: unknown user: striparr
striparr                | [listener] s6-envuidgid: fatal: unknown user: striparr
striparr                | [worker] s6-envuidgid: fatal: unknown user: striparr
striparr                | [listener] s6-envuidgid: fatal: unknown user: striparr
striparr                | [worker] s6-envuidgid: fatal: unknown user: striparr
```

This configuration works just fine with the linuxserver.io `sonarr` / `radarr` images.
